# @Description:         This script would to open JavaDoc generated by doc/make.javadoc.sh script
# @Author:              Quentin Le Bian <quentpilot>
# @Email:               quentin.lebian@pilotaweb.fr
# @Project:             LiveCurrencyConverter
# @About:               You're welcome to hack and code as your are each of theses sources files <3:p|--<;
# @Filename:            open.javadoc.sh
# @Date:                2017-11-04T16:51:25+01:00
# @Last modified by:    quentpilot
# @Last modified time:  2017-11-04T16:53:21+01:00
# @License:             MIT
# @See:                 projects.quentinlebian.fr/LiveCurrencyConverter


firefox javadoc/www/index.html
